//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesglosCompra
    {
        public int Id { get; set; }
        public int RefCompraId { get; set; }
        public int RefCompraOrigId { get; set; }
        public double Participacions { get; set; }
        public double ParticipacionsOrig { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Moviment Moviment { get; set; }
        public virtual Moviment MovimentOrig { get; set; }
    }
}
