//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesgloçCompresMoviments
    {
        public int Id { get; set; }
        public int IdProdMov { get; set; }
        public string ProdMov { get; set; }
        public int IdMov { get; set; }
        public System.DateTime DataMov { get; set; }
        public decimal PartsMov { get; set; }
        public decimal PUMov { get; set; }
        public int IdProdOrig { get; set; }
        public string ProdOrig { get; set; }
        public int IdOrig { get; set; }
        public System.DateTime DataOrig { get; set; }
        public decimal PartsOrig { get; set; }
        public decimal PUOrig { get; set; }
    }
}
