//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moviment
    {
        public Moviment()
        {
            this.DesglosCompres = new HashSet<DesglosCompra>();
            this.DesglosCompresOrig = new HashSet<DesglosCompra>();
            this.MovimentRefVenda1 = new HashSet<Moviment>();
        }
    
        public int Id { get; set; }
        public int UsuariId { get; set; }
        public int ProdId { get; set; }
        public TipusMoviment TipusMoviment { get; set; }
        public Nullable<int> MovimentRefVendaId { get; set; }
        public System.DateTime Data { get; set; }
        public double Participacions { get; set; }
        public Nullable<double> PreuParticipacioOrigen { get; set; }
        public double PreuParticipacio { get; set; }
        public double CanviAplicat { get; set; }
        public Nullable<double> Despeses { get; set; }
        public string Descripcio { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<DesglosCompra> DesglosCompres { get; set; }
        public virtual ICollection<DesglosCompra> DesglosCompresOrig { get; set; }
        public virtual Producte Prod { get; set; }
        public virtual ICollection<Moviment> MovimentRefVenda1 { get; set; }
        public virtual Moviment MovimentRefVendaN { get; set; }
        public virtual Usuari Usuari { get; set; }
    }
}
