//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Producte
    {
        public Producte()
        {
            this.MovimentsProducte = new HashSet<Moviment>();
            this.Valoracions = new HashSet<Valoracio>();
            this.MovimentsTraspas = new HashSet<Moviment>();
        }
    
        public int Id { get; private set; }
        public int EmpresaId { get; private set; }
        public byte[] RowVersion { get; private set; }
        public Nullable<int> OrdreGrid { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Moviment> MovimentsProducte { get; set; }
        public virtual ICollection<Valoracio> Valoracions { get; set; }
        public virtual ICollection<Moviment> MovimentsTraspas { get; set; }
    }
}
