//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inversions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productes_ProdFons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productes_ProdFons()
        {
            this.Gestors = new HashSet<Gestor>();
        }
    
        public string Nom { get; set; }
        public string ISIN { get; set; }
        public string Descripcio { get; set; }
        public int Id { get; set; }
    
        public virtual Producte Producte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gestor> Gestors { get; set; }
    }
}
